apiVersion: grafana.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: grafana-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: grafana-creds
      namespace: crossplane
      key: credentials
